name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Set up Pages
      - uses: actions/configure-pages@v3

      # 3. Upload frontend folder as artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./frontend

      # 4. Deploy to GitHub Pages
      - uses: actions/deploy-pages@v2
